ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^\.napari-hub/.*
      - id: check-yaml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/tlambert03/napari-plugin-checks
    rev: v0.3.0
    hooks:
      - id: napari-plugin-checks
